### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by ajithkpistar** [kdechant/angular2-http-demo#1]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'lite' ]
2 info using npm@3.8.2
3 info using node@v0.12.12
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prelite', 'lite', 'postlite' ]
6 info lifecycle angular2-http-demo@0.1.0~prelite: angular2-http-demo@0.1.0
7 silly lifecycle angular2-http-demo@0.1.0~prelite: no script for prelite, continuing
8 info lifecycle angular2-http-demo@0.1.0~lite: angular2-http-demo@0.1.0
9 verbose lifecycle angular2-http-demo@0.1.0~lite: unsafe-perm in lifecycle true
10 verbose lifecycle angular2-http-demo@0.1.0~lite: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ajith/Documents/dont knw/angular2-http-demo/node_modules/.bin:/usr/bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ajith/Documents/dont knw/angular2-http-demo/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
11 verbose lifecycle angular2-http-demo@0.1.0~lite: CWD: /home/ajith/Documents/dont knw/angular2-http-demo
12 silly lifecycle angular2-http-demo@0.1.0~lite: Args: [ '-c', 'lite-server' ]
13 silly lifecycle angular2-http-demo@0.1.0~lite: Returned: code: 1  signal: null
14 info lifecycle angular2-http-demo@0.1.0~lite: Failed to exec lite script
15 verbose stack Error: angular2-http-demo@0.1.0 lite: `lite-server`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
15 verbose stack     at EventEmitter.emit (events.js:110:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at ChildProcess.emit (events.js:110:17)
15 verbose stack     at maybeClose (child_process.js:1019:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
16 verbose pkgid angular2-http-demo@0.1.0
17 verbose cwd /home/ajith/Documents/dont knw/angular2-http-demo
18 error Linux 4.2.0-34-generic
19 error argv "node" "/usr/bin/npm" "run" "lite"
20 error node v0.12.12
21 error npm  v3.8.2
22 error code ELIFECYCLE
23 error angular2-http-demo@0.1.0 lite: `lite-server`
23 error Exit status 1
24 error Failed at the angular2-http-demo@0.1.0 lite script 'lite-server'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the angular2-http-demo package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     lite-server
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs angular2-http-demo
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls angular2-http-demo
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by karolmie1** [comment]
I had a different problem: angular was unable to resolve Promises, and Maps as a result of lack of shims.
Some packages were probably installed in too new version by npm, and that caused the build to break.

It would be cool if you could lock the correct versions of packages for this great example - for example doing it with yarn. Yarn is really cool wrapper for npm that allows builds to be much faster and more consistent.

**Comment by laryts** [comment]
How is your php file of API?
