### ISSUE TITLE
Nice but why not auto sync

### ISSUE THREAD

**Issue by rajeget** [kdechant/angular2-http-demo#2]
Hi 
Thanks for the code, and sharing support . But its a async ajax request. How to update the data model back to server ( using POST / websocket) and keep consistency ?

-Raje

**Comment by kdechant** [comment]
I haven't actually done a POST request with Angular 2 yet. The documentation (https://angular.io/docs/ts/latest/api/http/Http-class.html) shows methods like http.post(), http.put(), http.delete() and so on which should handle saving data.

You probably _could_ use Observable.forkJoin() with verbs other than GET, but it sounds a little dangerous. If an error happened in one of the requests, you could get into a state where one model saved on the back-end and another didn't, which wouldn't be ideal.
